#!/usr/bin/env python

import random
import sys
import time


def main():
  words = "filling space and time".split()
  while True:
    sys.stdout.write(random.choice(words))
    sys.stdout.flush()
    time.sleep(random.uniform(0, 1))


if __name__ == '__main__':
  main()

