#!/usr/bin/env python


"""Sing 'Duke of Earl'"""


import subprocess
import sys
import time


interval = 0.1
interval_short = 0.00


def main():
  while True:
    phrase()
    time.sleep(interval)


def phrase():
 for i in range(0, 3):
   duke()
 duke_of_earl()
 for i in range(0, 2):
   for j in range(0, 2):
     duke()
   duke_of_earl()


def duke():
  print "duke"
  say("duke")
  time.sleep(interval)


def duke_of_earl():
  print "duke",
  sys.stdout.flush()
  say("duke")
  time.sleep(interval_short)
  print "of",
  say("of")
  sys.stdout.flush()
  time.sleep(interval_short)
  print "earl"
  sys.stdout.flush()
  say("earl")
  time.sleep(interval)


def say(x):
  subprocess.call(['/usr/bin/say', '-v', 'Cello', x])

 
if __name__ == '__main__':
  main()

