#!/usr/bin/env python

"""Calculate e**x."""

import argparse
import sys


def main():
    parser = argparse.ArgumentParser(description='Calculate e**x.')
    parser.add_argument('x', metavar='X', type=int, nargs=1,
                        help='power of e**x')
    parser.add_argument('n', metavar='N', type=int, nargs=1,
                        help='number of terms in expansion')
    args = parser.parse_args()

    x = args.x[0]
    n = args.n[0]

    s = 1.0
    fac = 1.0
    pow = x
    for i in range(0, n):
        s += pow / fac
        pow *= x
        fac *= (i + 2)
    print s

    return 0


if __name__ == '__main__':
    sys.exit(main())
