#!/usr/bin/env python


def main():
  d1 = [1, 1]
  d2 = [1, 1]
  e = [1, 0, 0, 1]
  assert mult(d1, d2) == e


def mult(d1, d2):
  assert len(d1) == len(d2)
  n = len(d1)
  r = [0 for i in range(0, 2*n)]
  x = 0
  for i in range(0, 2*n):
    for j in range(max(0, i+1-n), min(i+1, n)):
      k = i - j
      x = x + bmult(d1[j], d2[k])
    r[i] = x % 2
    x = x / 2
  return r


def bmult(x, y):
   if x & y:
     return 1
   else:
     return 0
  


if __name__ == '__main__':
   main()

