#!/usr/bin/env python

"""Calculate catalan's constant"""

import argparse
import sys


def main():
    parser = argparse.ArgumentParser(description="Calculate Catalan's constant to n terms.")
    parser.add_argument('n', metavar='NUM_TERMS', type=int, nargs=1,
                        help='Number of terms in approximation')
    args = parser.parse_args()

    n = args.n[0]
    if n < 1:
	print >> sys.stderr, "NUM_TERMS must be at least 1"
	sys.exit(-127)

    s = 0
    sgn = 1
    for i in range(0, n):
        lt = (i * 2 + 1) ** 2
	s += sgn * 1.0/float(lt)
        sgn = sgn * -1

    print s


if __name__ == '__main__':
    sys.exit(main())
