#!/usr/bin/env python

"""Sleep sort."""

import threading
import time
import sys


def main():
    unsorted_data = [8, 7, 12, 1, 3]
    sorted_data = []
    lock = threading.Lock()
    start_delay = len(unsorted_data) * 0.001
    st = []
    for value in unsorted_data:
        st.append(threading.Thread(target=sleep, args=(value, start_delay, lock, sorted_data)))
    for t in st:
        t.start()
    for t in st:
        t.join()
    print ",".join(str(x) for x in sorted_data)


def sleep(value, start_delay, sortlock, sorted_data):
    time.sleep(value * 0.001 + start_delay)
    with sortlock:
        sorted_data.append(value)


if __name__ == '__main__':
    sys.exit(main())
