#!/usr/bin/python

import argparse
import calendar
import datetime
import re
import sys


def main():
    parser = argparse.ArgumentParser(description='Interconvert dates and timestamps')
    parser.add_argument('t', metavar='TIMESTAMP', type=str, nargs=1,
                        help='value to convert')
    args = parser.parse_args()
    ts = args.t[0]
    if re.search(r'^\d+$', ts):
        print datetime.datetime.utcfromtimestamp(float(ts))
        return 0
    else:
        fmt = '%Y-%m-%d %H:%M:%S'
        d = datetime.datetime.strptime(ts, fmt)
        print calendar.timegm(d.timetuple())
        return 0


if __name__ == '__main__':
    sys.exit(main())
