#!/usr/bin/env python

"""Gernetae all permutations of a string."""

import sys


def main():
  s = "abc"
  for p in permute(s):
    print p


def permute(s):
  if len(s) == 1:
    yield s
    return
  for i in range(0, len(s)):
   c = s[i]
   for p in permute(s[:i] + s[i+1:]):
     yield c + p

    
if __name__ == '__main__':
    sys.exit(main())
