#!/usr/bin/env python

"""A demonstration of late-night laziness, but an epic party too."""


import sys


INDENT = '  '


def main():
    poem = """
Once I was alone
I found myself
[+]with
[++]others
Not so alone
[+]To myself I stayed
[++]But I could not remain
Within the shell
[+]And so they drew me out
[++]As I let them in
"""[1:-1]
    print poem.replace('[+]', INDENT).replace('[++]', INDENT * 2)


if __name__ == '__main__':
    sys.exit(main())