#!/usr/bin/env python

import sys



def solve(f):
    crdt = readint(f)
    ni = readint(f)
    itms = readints(f, ni)
    sln =
    return "%d %s %s" % (crdt, ni, itms)

def main(f):
  ncl = readline(f)
  nc = int(ncl)
  for i in range(1, nc+1):
    res = solve(f)
    print "Case #%d: %s" % (i, res)

def readline(f):
  return f.readline().replace('\n', '')


def readint(f):
  return readints(f, 1)[0]


def readints(f, n):
  itms = [int(x) for x in readline(f).split()]
  assert len(itms) == n, "wrong input count: expected %d ints but got %d" % (n, len(itms))
  return itms


if __name__ == '__main__':
   main(sys.stdin)


